;EXPT 2D: Parallel port interfacing of LEDs
;PROBLEM STATEMENT: ALP FOR HEXADECIMAL NUMBER DISPLAY ON LEDS CONNECTED TO PORT 2
;NAME: Anil Rajpurohit
;BATCH: B2, ROLL NO :312046
;DATE OF PERFORMANCE: 11/07/18


			ORG 0000H
				
			MOV P2,#00H   		;MOVE 00H TO PORT2
	 HERE:  INC P2				;INCREMENT VALUE TO PORT 2
			ACALL DELAY			;DELAY SUBROUTINE
			SJMP HERE 
			
			
	DELAY:  MOV R0,#14	 		;DELAY USING TIMER
			MOV TMOD,#01H		;TIMER 0 ,MODE 1 IS SELECTED 
	   L1:  MOV TL0,#00			;INITIALISE TL0 TO 00H
			MOV TH0,#00			;INITIALISE TH0 TO 00H
			SETB TR0			;START TIMER
	   L2:  JNB TF0,L2 			;WAIT TILL DELAY END
			CLR TR0				;STOP TMER
			CLR TF0				;CLEAR TF0 FLAG
			DJNZ R0,L1			;RUN LOOP `14 TIMES
			
			RET			
			END			 