;EXPERIMENT_3A: WRITE AN ALP TO INTERFACE DAC0808 AND GENERATE SQUARE WAVE OF 1KHZ
;NAME: ANIL RAJPUROHIT
;ROLL N0: 312046
;BATCH: B2
;DATE OF PERFORMANCE: 1/8/2018
 
			ORG 000H		
				
		L1: MOV P1,#0		; COPY ACC TO PORT 1
			ACALL DELAY		; CALL DELAY OF 1ms
			MOV P1,#0FFH	; STORE 255 TO THE PORT 1
			ACALL DELAY		; CALL DELAY OF 1ms
			SJMP L1			; LOOP CONTINOUSLY
 
	 DELAY:	MOV R1,#223D	; STORE VALUE 223 TO R1
		L2: DJNZ R1,L2	    ; WAIT UNTIL R1 IS NOT EQUAL TO 0


			RET				
			END				
			 